[project]
name = "git-dev-metrics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.128.0",
    "keyring>=25.7.0",
    "pygithub>=2.8.1",
    "pyright>=1.1.408",
    "python-dateutil>=2.9.0.post0",
    "requests>=2.32.5",
    "rich>=14.3.1",
    "ruff>=0.15.0",
    "typer>=0.21.1",
]

[project.optional-dependencies]
test = [
    "pytest>=9.0.2",
    "pytest-mock>=3.10.0",
    "pytest-cov>=4.0.0",
    "responses>=0.24.0",
]

[tool.basedpyright]
venvPath = "."
venv = ".venv"
typeCheckingMode = "standard"

[dependency-groups]
dev = [
    "freezegun>=1.5.5",
    "pyright>=1.1.408",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
    "responses>=0.25.8",
    "ruff>=0.15.0",
]
